on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
name: Build and Test
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        with:
          ruby-version: 3.1.6
        run: gem install rubocop
      - name: Rubocop
        run: rubocop